---
# Install and configure irssi

- name: Install irssi through apt-get
  apt: name=irssi
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Install irssi through brew
  homebrew: name=irssi
  when: ansible_os_family == "Darwin"

- name: See if wrong .irssi dir
  stat: path=~/.irssi
  register: old_irssi

- name: Remove old .irssi dir if necessary
  shell: mv ~/.irssi ~/.irssi_old
  when: 'old_irssi.stat.exists and ".dot" not in old_irssi.stat.lnk_source'

- name: Link .irssi dir
  file: src=~/.dotfiles/irssi dest=~/.irssi state=link
