---
# Install ZSH and prompt

- name: Install ZSH
  apt: name=zsh
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Clone Prezto repo
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto

- name: Find runcom Prezto files
  shell: find ~/.zprezto/runcoms -type f -name 'z*'
  register: file_list

- name: Link Prezto files
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_items: file_list.stdout_lines

- name: Set default shell to ZSH
  user: name={{ ansible_user_id }} shell=/bin/zsh
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Download pure theme
  get_url: url=https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh
           dest=~/.zprezto/modules/prompt/functions/prompt_pure_setup

- name: See if wrong .zshrc
  stat: path=~/.zshrc
  register: old_zshrc

- name: Remove old .zshrc if necessary
  shell: mv ~/.zshrc ~/.zshrc_old
  when: '"runcoms" in old_zshrc.stat.lnk_source'

- name: Link .zshrc
  file: src=~/.dotfiles/zsh/zshrc dest=~/.zshrc state=link

- name: See if wrong .zpreztorc
  stat: path=~/.zpreztorc
  register: old_zpreztorc

- name: Remove old .zshrc if necessary
  shell: mv ~/.zpreztorc ~/.zpreztorc_old
  when: '"runcoms" in old_zpreztorc.stat.lnk_source'

- name: Link .zpreztorc
  file: src=~/.dotfiles/zsh/zpreztorc dest=~/.zpreztorc state=link
