# Source all *.zsh files in this dir
for file in ~/.dotfiles/zsh/*.zsh{rc,}
	do source $file
done

# Source Prezto if available
# Has to be done after node.zshrc is loaded
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ `uname` == 'Darwin' ]]; then
	[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
elif [[ -s /usr/share/autojump/autojump.sh ]]; then
	. /usr/share/autojump/autojump.sh
fi

# For super secret stuff
if [[ -a ~/.localrc ]] then
	source ~/.localrc
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line
