# Source all *.zsh files in this dir
for file in ~/.dotfiles/zsh/*.zshrc
	do source $file
done

# For super secret stuff
if [[ -a ~/.localrc ]] then
	source ~/.localrc
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# added by travis gem
[ -f /Users/callumacrae/.travis/travis.sh ] && source /Users/callumacrae/.travis/travis.sh

export NVM_DIR="/Users/callumacrae/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
