# Source all *.zsh files in this dir
for file in ~/.dotfiles/zsh/*.zshrc
	do source $file
done

# For super secret stuff
if [[ -a ~/.localrc ]] then
	source ~/.localrc
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# added by travis gem
[ -f /Users/callumacrae/.travis/travis.sh ] && source /Users/callumacrae/.travis/travis.sh

