---
# Install and configure git and hub

- name: Install hub
  homebrew: name=hub
  when: ansible_os_family == "Darwin"

- name: Install git
  apt: name=git
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Get .git-completion.sh
  get_url: \
    url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
    dest=~/.zsh/_git

- name: Install hub dependencies
  apt: name=rake
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Clone hub repo
  git: repo=https://github.com/github/hub.git
       dest=~/.hub-repo
  when: ansible_os_family == "Debian"
  sudo: yes # So that it's in the correct place

- name: Install hub
  shell: rake install prefix=/usr/local chdir=~/.hub-repo
  when: ansible_os_family == "Debian"
  sudo: yes

- name: Add global gitignore
  file: src=~/.dotfiles/misc/gitignore_global dest=~/.gitignore_global state=link

- name: Use global gitignore
  shell: git config --global core.excludesfile ~/.gitignore_global
